### ISSUE TITLE
[question] Why use lightningcss-wasm for SSR?

### ISSUE THREAD

**Issue by coindegen** [taggon/bun-style-loader#3]
First off, thanks for the plugin. I was worried I'd have to write this myself so appreciate the effort. It is performing great so far, I just had a question out of curiosity.

Is there any reason you're dynamically importing the WASM version of lightningcss? https://github.com/taggon/bun-style-loader/blob/main/src/compile-css.ts#L9

Based on the docs, that build is meant for Deno or browser environments: https://lightningcss.dev/docs.html#from-deno-or-in-browser

I would have assumed we'd be using the lightningcss package instead, and there'd be some benefits in doing so. In my codebase I'm inserting all the CSS on the server like this:

```tsx
import styles, { code } from "./ProgressMeter.module.css";

export const ProgressMeter = ({
  currentVal,
  maxVal,
}: {
  currentVal: number;
  maxVal: number;
}) => {
  return (
    <>
      <style safe>{code}</style>
      <div
        class={styles["progress-meter-host"]}
      >
        <div class={styles.handle}></div>
        <div class={styles.meter}></div>
      </div>
    </>
  );
};
```

and therefore have no need for `insertStyleElement()` or any other browser-specific functionality.

**Comment by taggon** [comment]
Hi there. Thanks for using my package. 😄 

There are a few reasons why I decided to use the WASM variants of lightningcss for my package:

1. Bun is not a runtime officially supported by LightningCSS. You won't find Bun in the official docs.
2. In my experience, native modules sometimes cause compatibility problems when an application runs on different platforms. WASM is usually better for compatibility. IMHO, Bun is not as stable as Node (no offense. I love it) yet, so my module might be broken with any future version of Bun if it depends on a native Lightning CSS.
3. The WASM version is fast enough.

I would use the lightningcss package instead in the future version, once Lightning CSS announces they're officially supporting Bun.

**Comment by taggon** [comment]
> I would have assumed we'd be using the lightningcss package instead, and there'd be some benefits in doing so. In my codebase I'm inserting all the CSS on the server like this

The code looks neat. I'd like to consider supporting that.

**Comment by coindegen** [comment]
> I would use the lightningcss package instead in the future version, once Lightning CSS announces they're officially supporting Bun.

Thanks for sharing your thought process. Those points all make sense, glad to learn that you considered the native package and that a future Bun release is on your radar. If it does ever come out I'll be happy to help benchmark it. Cheers.
